// GENERATED - DO NOT EDIT.
// Regenerate with: npm run gen:contracts
// Source: packages/contracts/openapi.json (see PROVENANCE)
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/append-message-id-list/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Append Message Id List */
        put: operations["append_message_id_list_api_v1_append_message_id_list__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/approve-match/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Approve Match */
        put: operations["approve_match_api_v1_approve_match__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assign-discord-id-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign Discord Id All */
        put: operations["assign_discord_id_all_api_v1_assign_discord_id_all__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assign-discord-id/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign Discord Id */
        put: operations["assign_discord_id_api_v1_assign_discord_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assign-sub/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign Sub */
        put: operations["assign_sub_api_v1_assign_sub__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/accounts/discord/{discord_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Account By Discord */
        get: operations["lookup_account_by_discord_api_v1_auth_admin_accounts_discord__discord_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/accounts/linked-account/{linked_account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Account By Linked Account */
        get: operations["lookup_account_by_linked_account_api_v1_auth_admin_accounts_linked_account__linked_account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/accounts/steam/{steam_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Account By Steam */
        get: operations["lookup_account_by_steam_api_v1_auth_admin_accounts_steam__steam_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/admin/manual-registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Manual Registration */
        post: operations["create_manual_registration_api_v1_auth_admin_manual_registrations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/manual-registration-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Self Service Registration */
        post: operations["create_self_service_registration_api_v1_auth_manual_registration_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/rank-role-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rank Role Request */
        post: operations["create_rank_role_request_api_v1_auth_rank_role_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registration-operations/{operation_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Registration Operation */
        post: operations["finalize_registration_operation_api_v1_auth_registration_operations__operation_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registration-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Registration Session */
        post: operations["create_registration_session_api_v1_auth_registration_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registration-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Registration Session */
        get: operations["get_registration_session_api_v1_auth_registration_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registration-sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Registration Session */
        post: operations["complete_registration_session_api_v1_auth_registration_sessions__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/change-order/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Order */
        put: operations["change_order_api_v1_change_order__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contest-report/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Contest Report */
        put: operations["contest_report_api_v1_contest_report__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/delete-pending-match/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Delete Pending Match */
        put: operations["delete_pending_match_api_v1_delete_pending_match__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/get-leaderboard-ranking/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Get Leaderboard Ranking */
        put: operations["get_leaderboard_ranking_api_v1_get_leaderboard_ranking__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/get-match/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Get Match */
        put: operations["get_match_api_v1_get_match__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/get-user-stats-batch/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Get Users Stats Batch */
        put: operations["put_get_users_stats_batch_api_v1_get_user_stats_batch__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/get-user-stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Get User Stats */
        put: operations["put_get_user_stats_api_v1_get_user_stats__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Suspensions */
        get: operations["get_active_suspensions_api_v1_infractions_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overdue Suspensions */
        get: operations["get_overdue_suspensions_api_v1_infractions_overdue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{discord_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record */
        get: operations["get_record_api_v1_infractions__discord_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{discord_id}/add-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Days */
        post: operations["add_days_api_v1_infractions__discord_id__add_days_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{discord_id}/flat/{flat_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Flat Suspension */
        post: operations["record_flat_suspension_api_v1_infractions__discord_id__flat__flat_type__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{discord_id}/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pending Suspension */
        get: operations["get_pending_suspension_api_v1_infractions__discord_id__pending_get"];
        put?: never;
        /** Create Pending Suspension */
        post: operations["create_pending_suspension_api_v1_infractions__discord_id__pending_post"];
        /** Delete Pending Suspension */
        delete: operations["delete_pending_suspension_api_v1_infractions__discord_id__pending_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{discord_id}/remove-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove Days */
        post: operations["remove_days_api_v1_infractions__discord_id__remove_days_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{discord_id}/remove-tier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remove Tier */
        post: operations["remove_tier_api_v1_infractions__discord_id__remove_tier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{discord_id}/tier/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Tier Infraction */
        post: operations["record_tier_infraction_api_v1_infractions__discord_id__tier__category__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/infractions/{discord_id}/unsuspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unsuspend */
        post: operations["unsuspend_api_v1_infractions__discord_id__unsuspend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/remove-sub/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Remove Sub */
        put: operations["remove_sub_api_v1_remove_sub__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/revert-match/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Revert Match */
        put: operations["revert_match_api_v1_revert_match__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/set-player-order/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Player Order */
        put: operations["set_player_order_api_v1_set_player_order__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Users Stats Batch */
        post: operations["get_users_stats_batch_api_v1_stats_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/reset/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reset User Stats */
        put: operations["reset_user_stats_api_v1_stats_reset_user_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/team-gen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Team Gen */
        post: operations["get_team_gen_api_v1_stats_team_gen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Stats */
        get: operations["get_user_stats_api_v1_stats_user_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trigger-quit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Trigger Quit */
        put: operations["trigger_quit_api_v1_trigger_quit__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/update-match/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Match */
        put: operations["update_match_api_v1_update_match__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload-game-report/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Game Report */
        post: operations["upload_game_report_api_v1_upload_game_report__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/discord/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discord Oauth Callback */
        get: operations["discord_oauth_callback_oauth_discord_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveSuspension */
        ActiveSuspension: {
            /** Discord Id */
            discord_id: string;
            /**
             * Ends
             * Format: date-time
             */
            ends: string;
        };
        /** AffectedPlayerRating */
        AffectedPlayerRating: {
            /** Discord Id */
            discord_id: string;
            /** Rating Mu */
            rating_mu: number;
        };
        /** AppendDiscordMessageID */
        AppendDiscordMessageID: {
            /** Discord Message Id */
            discord_message_id: string[];
            /** Match Id */
            match_id: string;
        };
        /** ApproveMatch */
        ApproveMatch: {
            /** Approver Discord Id */
            approver_discord_id: string;
            /** Match Id */
            match_id: string;
        };
        /** AssignDiscordId */
        AssignDiscordId: {
            /** Discord Message Id */
            discord_message_id: string;
            /** Match Id */
            match_id: string;
            /** Player Discord Id */
            player_discord_id: string;
            /** Player Id */
            player_id: string;
        };
        /** AssignDiscordIdAll */
        AssignDiscordIdAll: {
            /** Discord Id List */
            discord_id_list: string[];
            /** Discord Message Id */
            discord_message_id: string;
            /** Match Id */
            match_id: string;
        };
        /** AssignSub */
        AssignSub: {
            /** Discord Message Id */
            discord_message_id: string;
            /** Match Id */
            match_id: string;
            /** Sub In Id */
            sub_in_id: string;
            /** Sub Out Discord Id */
            sub_out_discord_id: string;
        };
        /** BatchStatsRequest */
        BatchStatsRequest: {
            /** Civ Version */
            civ_version: string;
            /** Discord Ids */
            discord_ids: string[];
            /** Game Type */
            game_type: string;
        };
        /** BatchStatsResponse */
        BatchStatsResponse: {
            /** Civ Version */
            civ_version: string;
            /** Game Type */
            game_type: string;
            /** Results */
            results: components["schemas"]["UserStatsResponse"][];
        };
        /** Body_get_match_api_v1_get_match__put */
        Body_get_match_api_v1_get_match__put: {
            /** Match Id */
            match_id: string;
        };
        /** Body_put_get_user_stats_api_v1_get_user_stats__put */
        Body_put_get_user_stats_api_v1_get_user_stats__put: {
            /** Civ Version */
            civ_version?: string | null;
            /** Discord Id */
            discord_id: string;
            /** Game Type */
            game_type: string;
            /** Version */
            version?: string | null;
        };
        /** Body_put_get_users_stats_batch_api_v1_get_user_stats_batch__put */
        Body_put_get_users_stats_batch_api_v1_get_user_stats_batch__put: {
            /** Civ Version */
            civ_version?: string | null;
            /** Discord Id List */
            discord_id_list: string[];
            /** Game Type */
            game_type: string;
            /** Version */
            version?: string | null;
        };
        /** Body_upload_game_report_api_v1_upload_game_report__post */
        Body_upload_game_report_api_v1_upload_game_report__post: {
            /** Discord Message Id */
            discord_message_id: string;
            /**
             * File
             * Format: binary
             */
            file: string;
            /** Is Cloud */
            is_cloud: string;
            /** Reporter Discord Id */
            reporter_discord_id: string;
        };
        /** ChangeOrder */
        ChangeOrder: {
            /** Discord Message Id */
            discord_message_id: string;
            /** Match Id */
            match_id: string;
            /** New Order */
            new_order: string;
        };
        /** CompleteRegistrationSessionRequest */
        CompleteRegistrationSessionRequest: {
            /** Discord User Id */
            discord_user_id: string;
        };
        /** ContestReport */
        ContestReport: {
            /** Contestor Discord Id */
            contestor_discord_id: string;
            /** Reason */
            reason: string;
        };
        /** ContestReportRequest */
        ContestReportRequest: {
            /** Contestor Discord Id */
            contestor_discord_id: string;
            /** Discord Message Id */
            discord_message_id: string;
            /** Match Id */
            match_id: string;
            /** Reason */
            reason: string;
        };
        /** CreatePendingSuspensionRequest */
        CreatePendingSuspensionRequest: {
            /** Punishment Type */
            punishment_type: string;
            /** Reason */
            reason?: string | null;
        };
        /** CreateRegistrationSessionRequest */
        CreateRegistrationSessionRequest: {
            /** Discord User Id */
            discord_user_id: string;
            game: components["schemas"]["SupportedGame"];
            /** @default steam */
            platform: components["schemas"]["RegistrationPlatform"];
        };
        /** DeletePendingMatch */
        DeletePendingMatch: {
            /** Match Id */
            match_id: string;
        };
        /** DiscordAccountLookupHit */
        DiscordAccountLookupHit: {
            /** Discord Display Name */
            discord_display_name?: string | null;
            /** Discord Id */
            discord_id: string;
            /** Discord Username */
            discord_username?: string | null;
            /** Registrations */
            registrations?: components["schemas"]["RegistrationSummary"][];
        };
        /** DiscordLookupResponse */
        DiscordLookupResponse: {
            /** Discord Display Name */
            discord_display_name?: string | null;
            /** Discord Id */
            discord_id: string;
            /** Discord Username */
            discord_username?: string | null;
            /** Linked Accounts */
            linked_accounts?: components["schemas"]["LinkedAccountLookupHit"][];
        };
        /** DiscordOAuthCallbackResult */
        DiscordOAuthCallbackResult: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            /** Linked Account Id */
            linked_account_id?: string | null;
            /** Linked Account Name */
            linked_account_name?: string | null;
            platform: components["schemas"]["RegistrationPlatform"];
            /** Session Id */
            session_id: string;
            status: components["schemas"]["RegistrationSessionStatus"];
        };
        /** FinalizeRegistrationOperationRequest */
        FinalizeRegistrationOperationRequest: {
            /** Applied Role Intents */
            applied_role_intents?: components["schemas"]["RoleIntent"][];
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            /**
             * Result
             * @enum {string}
             */
            result: "succeeded" | "failed";
        };
        /** FlatSuspensionResponse */
        FlatSuspensionResponse: {
            /** Days Added */
            days_added: number;
            /** Discord Id */
            discord_id: string;
            /**
             * Ends
             * Format: date-time
             */
            ends: string;
            /** Suspended */
            suspended: boolean;
            type: components["schemas"]["FlatType"];
        };
        /**
         * FlatType
         * @enum {string}
         */
        FlatType: "smurf" | "oversub" | "comp";
        /** GetLeaderboardRequest */
        GetLeaderboardRequest: {
            /** Game */
            game: string;
            /** Game Mode */
            game_mode: string;
            /** Game Type */
            game_type: string;
            /** Is Combined */
            is_combined: boolean;
            /** Is Seasonal */
            is_seasonal: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardRankingResponse */
        LeaderboardRankingResponse: {
            /** Last Updated */
            last_updated: number;
            /** Rankings */
            rankings: components["schemas"]["PlayerLeaderboard"][];
        };
        /** LinkedAccountLookupHit */
        LinkedAccountLookupHit: {
            /** Linked Account Id */
            linked_account_id: string;
            /** Linked Account Name */
            linked_account_name?: string | null;
            linked_platform?: components["schemas"]["RegistrationPlatform"] | null;
            /** Registrations */
            registrations?: components["schemas"]["RegistrationSummary"][];
        };
        /** LinkedAccountLookupResponse */
        LinkedAccountLookupResponse: {
            /** Discord Accounts */
            discord_accounts?: components["schemas"]["DiscordAccountLookupHit"][];
            /** Linked Account Id */
            linked_account_id: string;
            /** Linked Account Name */
            linked_account_name?: string | null;
            linked_platform?: components["schemas"]["RegistrationPlatform"] | null;
        };
        /**
         * ManualRegistrationChoice
         * @description Staff-facing platform choice for `/manual-register`.
         *
         *     Distinct from RegistrationPlatform because "Steam Family Share" is not a stored
         *     platform: it persists as linked_platform=steam with method=admin_steam_family_share.
         *     The backend owns the mapping to (stored platform, method) via `resolved()`.
         * @enum {string}
         */
        ManualRegistrationChoice: "steam" | "steam_family_share" | "2k";
        /** ManualRegistrationRequest */
        ManualRegistrationRequest: {
            /** Actor Discord Id */
            actor_discord_id: string;
            /** Discord Display Name */
            discord_display_name?: string | null;
            /** Discord Username */
            discord_username?: string | null;
            game: components["schemas"]["SupportedGame"];
            platform: components["schemas"]["ManualRegistrationChoice"];
            /** Platform Account Id */
            platform_account_id: string;
            /** Platform Account Name */
            platform_account_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Subject Discord Id */
            subject_discord_id: string;
        };
        /** MatchResponse */
        MatchResponse: {
            /** Affected Players */
            affected_players?: components["schemas"]["AffectedPlayerRating"][] | null;
            /** Age */
            age?: string | null;
            /** Approved At */
            approved_at?: string | null;
            /** Approver Discord Id */
            approver_discord_id?: string | null;
            /** Contest Report List */
            contest_report_list: components["schemas"]["ContestReport"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Discord Messages Id List */
            discord_messages_id_list: string[];
            /** Flagged */
            flagged: boolean;
            /** Flagged By */
            flagged_by?: string | null;
            /** Game */
            game: string;
            /** Game Mode */
            game_mode: string;
            /** Is Cloud */
            is_cloud: boolean;
            /** Map Type */
            map_type: string;
            /** Match Id */
            match_id: string;
            /** Parser Version */
            parser_version: string;
            /** Players */
            players: components["schemas"]["PlayerSchema"][];
            /** Reporter Discord Id */
            reporter_discord_id: string;
            /** Save File Hash */
            save_file_hash: string;
            /** Turn */
            turn: number;
        };
        /** MatchUpdate */
        MatchUpdate: {
            /** Confirmed */
            confirmed?: boolean | null;
            /** Flagged */
            flagged?: boolean | null;
            /** Flagged By */
            flagged_by?: string | null;
            /** Match Id */
            match_id: string;
            /** Players */
            players?: components["schemas"]["PlayerSchema"][] | null;
        };
        /** ModifyDaysRequest */
        ModifyDaysRequest: {
            /** Days */
            days: number;
        };
        /** ModifyDaysResponse */
        ModifyDaysResponse: {
            /** Days Delta */
            days_delta: number;
            /** Discord Id */
            discord_id: string;
            /**
             * New Ends
             * Format: date-time
             */
            new_ends: string;
        };
        /** PendingSuspensionResponse */
        PendingSuspensionResponse: {
            /** Discord Id */
            discord_id: string;
            /** Punishment Type */
            punishment_type: string;
            /** Reason */
            reason: string | null;
        };
        /** PlayerLeaderboard */
        PlayerLeaderboard: {
            /** Discord Id */
            discord_id: string;
            /** First */
            first: number;
            /** Games Played */
            games_played: number;
            /** Rating */
            rating: number;
            /** Wins */
            wins: number;
        };
        /** PlayerSchema */
        PlayerSchema: {
            /** Civ */
            civ: string;
            /** Combined Delta */
            combined_delta?: number | null;
            /**
             * Delta
             * @default 0
             */
            delta: number;
            /** Discord Id */
            discord_id?: string | null;
            /**
             * Is Sub
             * @default false
             */
            is_sub: boolean;
            /** Leader */
            leader?: string | null;
            /** Placement */
            placement?: number | null;
            /** Player Alive */
            player_alive?: boolean | null;
            /** Quit */
            quit: boolean;
            /** Season Delta */
            season_delta?: number | null;
            /** Steam Id */
            steam_id?: string | null;
            /**
             * Subbed Out
             * @default false
             */
            subbed_out: boolean;
            /** Team */
            team: number;
            /** User Name */
            user_name?: string | null;
        };
        /** RankRoleRequest */
        RankRoleRequest: {
            /** Discord User Id */
            discord_user_id: string;
            game: components["schemas"]["SupportedGame"];
        };
        /** RecordFlatSuspensionRequest */
        RecordFlatSuspensionRequest: {
            /** Reason */
            reason?: string | null;
            /** Suspended Roles */
            suspended_roles?: string[];
        };
        /** RecordTierInfractionRequest */
        RecordTierInfractionRequest: {
            /** Reason */
            reason?: string | null;
            /** Suspended Roles */
            suspended_roles?: string[];
        };
        /**
         * RegistrationMethod
         * @description How a registration's account ownership was established.
         *
         *     Stored at registrations.<game>.method. Legacy records may carry the pre-change
         *     values "oauth" (treated as OAUTH_STEAM_API) or "manual_admin" (treated as attested).
         * @enum {string}
         */
        RegistrationMethod: "oauth_steam_api" | "admin_steam_family_share" | "admin_staff_attested" | "self_service_2k";
        /** RegistrationOperationResponse */
        RegistrationOperationResponse: {
            /** Discord User Id */
            discord_user_id: string;
            game: components["schemas"]["SupportedGame"];
            /** Linked Account Id */
            linked_account_id?: string | null;
            /** Linked Account Name */
            linked_account_name?: string | null;
            linked_platform?: components["schemas"]["RegistrationPlatform"] | null;
            /** Operation Id */
            operation_id: string;
            registration_method?: components["schemas"]["RegistrationMethod"] | null;
            /** Role Intents */
            role_intents: components["schemas"]["RoleIntent"][];
            status?: components["schemas"]["RegistrationOperationStatus"] | null;
            /** Steam Id */
            steam_id: string;
            /** Steam Name */
            steam_name?: string | null;
        };
        /**
         * RegistrationOperationStatus
         * @enum {string}
         */
        RegistrationOperationStatus: "pending" | "succeeded" | "failed";
        /**
         * RegistrationPlatform
         * @enum {string}
         */
        RegistrationPlatform: "steam" | "epic" | "2k" | "xbox";
        /** RegistrationSessionResponse */
        RegistrationSessionResponse: {
            /** Authorize Url */
            authorize_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Session Id */
            session_id: string;
        };
        /**
         * RegistrationSessionStatus
         * @enum {string}
         */
        RegistrationSessionStatus: "pending_auth" | "validating" | "validated" | "failed" | "expired" | "completed";
        /** RegistrationSessionStatusResponse */
        RegistrationSessionStatusResponse: {
            /** Discord Display Name */
            discord_display_name?: string | null;
            /** Discord Locale */
            discord_locale?: string | null;
            /** Discord Mfa Enabled */
            discord_mfa_enabled?: boolean | null;
            /** Discord Username */
            discord_username?: string | null;
            /** Discord Verified */
            discord_verified?: boolean | null;
            /** Expires At */
            expires_at?: string | null;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Message */
            failure_message?: string | null;
            game?: components["schemas"]["SupportedGame"] | null;
            /** Linked Account Id */
            linked_account_id?: string | null;
            /** Linked Account Name */
            linked_account_name?: string | null;
            platform?: components["schemas"]["RegistrationPlatform"] | null;
            /** Session Id */
            session_id: string;
            status: components["schemas"]["RegistrationSessionStatus"];
        };
        /** RegistrationSummary */
        RegistrationSummary: {
            game: components["schemas"]["SupportedGame"];
            /** Method */
            method?: string | null;
            /** Registered At */
            registered_at?: string | null;
        };
        /** RemoveSub */
        RemoveSub: {
            /** Discord Message Id */
            discord_message_id: string;
            /** Match Id */
            match_id: string;
            /** Sub Out Id */
            sub_out_id: string;
        };
        /** RemoveTierRequest */
        RemoveTierRequest: {
            category: components["schemas"]["TierCategory"];
        };
        /** RemoveTierResponse */
        RemoveTierResponse: {
            category: components["schemas"]["TierCategory"];
            /** Discord Id */
            discord_id: string;
            /** New Decays */
            new_decays: string | null;
            /** New Tier */
            new_tier: number;
            /** Was Changed */
            was_changed: boolean;
        };
        /** RevertMatchRequest */
        RevertMatchRequest: {
            /** Match Id */
            match_id: string;
        };
        /**
         * RoleIntent
         * @enum {string}
         */
        RoleIntent: "grant_civ6_rank" | "grant_civ7_rank" | "grant_novice" | "grant_server_news" | "grant_civ6_news" | "grant_civ7_news" | "grant_pc_steam" | "grant_2k_crossplatform" | "remove_non_verified";
        /**
         * SelfServiceRegistrationRequest
         * @description Civ7 non-Steam self-service registration (currently 2K only).
         *
         *     The Auth Bot supplies the Discord identity fields automatically. game/platform are
         *     accepted but the backend enforces game=civ7 + platform=2k (see ManualRegistrationService).
         */
        SelfServiceRegistrationRequest: {
            /** Discord Display Name */
            discord_display_name?: string | null;
            /** Discord User Id */
            discord_user_id: string;
            /** Discord Username */
            discord_username?: string | null;
            game: components["schemas"]["SupportedGame"];
            platform: components["schemas"]["RegistrationPlatform"];
            /** Platform Account Id */
            platform_account_id: string;
            /** Platform Account Name */
            platform_account_name?: string | null;
        };
        /** SetPlayerOrder */
        SetPlayerOrder: {
            /** Discord Message Id */
            discord_message_id: string;
            /** Match Id */
            match_id: string;
            /** Player Order */
            player_order: string;
        };
        /** StatRow */
        StatRow: {
            /** First */
            first: number;
            /** Games */
            games: number;
            /** Lastmodified */
            lastModified?: string | null;
            /** Mu */
            mu: number;
            /** Sigma */
            sigma: number;
            /**
             * Subbedin
             * @default 0
             */
            subbedIn: number;
            /**
             * Subbedout
             * @default 0
             */
            subbedOut: number;
            /** Wins */
            wins: number;
        };
        /** StatSet */
        StatSet: {
            duel?: components["schemas"]["StatRow"] | null;
            ffa?: components["schemas"]["StatRow"] | null;
            teamer?: components["schemas"]["StatRow"] | null;
        };
        /**
         * SupportedGame
         * @enum {string}
         */
        SupportedGame: "civ6" | "civ7";
        /** SuspensionRecordResponse */
        SuspensionRecordResponse: {
            /** Active Category */
            active_category: components["schemas"]["TierCategory"] | "flat" | null;
            /** Discord Id */
            discord_id: string;
            /** Ends */
            ends: string | null;
            /** Suspended */
            suspended: boolean;
            /** Suspended Roles */
            suspended_roles: string[];
        };
        /** TeamGenRequest */
        TeamGenRequest: {
            /** Civ Version */
            civ_version: string;
            /** Discord Ids */
            discord_ids: string[];
            /** Game Type */
            game_type: string;
        };
        /** TeamGenResponse */
        TeamGenResponse: {
            /** Civ Version */
            civ_version: string;
            /** Game Quality */
            game_quality: number;
            /** Game Type */
            game_type: string;
            /** Teams */
            teams: string[][];
        };
        /**
         * TierCategory
         * @enum {string}
         */
        TierCategory: "quit" | "minor" | "moderate" | "major" | "extreme";
        /** TierInfractionResponse */
        TierInfractionResponse: {
            active_category: components["schemas"]["TierCategory"] | null;
            category: components["schemas"]["TierCategory"];
            /** Days Added */
            days_added: number;
            /** Discord Id */
            discord_id: string;
            /** Ends */
            ends: string | null;
            /** Is Ban Threshold */
            is_ban_threshold: boolean;
            /** Is Warning Only */
            is_warning_only: boolean;
            /** Suspended */
            suspended: boolean;
            /** Tier */
            tier: number;
        };
        /** TriggerQuit */
        TriggerQuit: {
            /** Discord Message Id */
            discord_message_id: string;
            /** Match Id */
            match_id: string;
            /** Quitter Discord Id */
            quitter_discord_id: string;
        };
        /** UserStatsResponse */
        UserStatsResponse: {
            /** Civ Version */
            civ_version: string;
            /** Discord Id */
            discord_id: string;
            /** Game Type */
            game_type: string;
            lifetime: components["schemas"]["StatSet"];
            season: components["schemas"]["StatSet"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    append_message_id_list_api_v1_append_message_id_list__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AppendDiscordMessageID"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_match_api_v1_approve_match__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["ApproveMatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_discord_id_all_api_v1_assign_discord_id_all__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AssignDiscordIdAll"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_discord_id_api_v1_assign_discord_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AssignDiscordId"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_sub_api_v1_assign_sub__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AssignSub"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_account_by_discord_api_v1_auth_admin_accounts_discord__discord_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscordLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_account_by_linked_account_api_v1_auth_admin_accounts_linked_account__linked_account_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                linked_account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedAccountLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_account_by_steam_api_v1_auth_admin_accounts_steam__steam_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                steam_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkedAccountLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_registration_api_v1_auth_admin_manual_registrations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualRegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_self_service_registration_api_v1_auth_manual_registration_requests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelfServiceRegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rank_role_request_api_v1_auth_rank_role_requests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_registration_operation_api_v1_auth_registration_operations__operation_id__finalize_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeRegistrationOperationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_registration_session_api_v1_auth_registration_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRegistrationSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_registration_session_api_v1_auth_registration_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationSessionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_registration_session_api_v1_auth_registration_sessions__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteRegistrationSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_order_api_v1_change_order__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["ChangeOrder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contest_report_api_v1_contest_report__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["ContestReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pending_match_api_v1_delete_pending_match__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["DeletePendingMatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_ranking_api_v1_get_leaderboard_ranking__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["GetLeaderboardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardRankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match_api_v1_get_match__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_get_match_api_v1_get_match__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_get_users_stats_batch_api_v1_get_user_stats_batch__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_put_get_users_stats_batch_api_v1_get_user_stats_batch__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_get_user_stats_api_v1_get_user_stats__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_put_get_user_stats_api_v1_get_user_stats__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_suspensions_api_v1_infractions_active_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveSuspension"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overdue_suspensions_api_v1_infractions_overdue_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveSuspension"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_v1_infractions__discord_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuspensionRecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_days_api_v1_infractions__discord_id__add_days_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifyDaysRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModifyDaysResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_flat_suspension_api_v1_infractions__discord_id__flat__flat_type__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
                flat_type: components["schemas"]["FlatType"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordFlatSuspensionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlatSuspensionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_suspension_api_v1_infractions__discord_id__pending_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingSuspensionResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pending_suspension_api_v1_infractions__discord_id__pending_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePendingSuspensionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pending_suspension_api_v1_infractions__discord_id__pending_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_days_api_v1_infractions__discord_id__remove_days_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModifyDaysRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModifyDaysResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_tier_api_v1_infractions__discord_id__remove_tier_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveTierRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoveTierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_tier_infraction_api_v1_infractions__discord_id__tier__category__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
                category: components["schemas"]["TierCategory"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordTierInfractionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierInfractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsuspend_api_v1_infractions__discord_id__unsuspend_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                discord_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_sub_api_v1_remove_sub__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["RemoveSub"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_match_api_v1_revert_match__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["RevertMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_player_order_api_v1_set_player_order__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["SetPlayerOrder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_users_stats_batch_api_v1_stats_batch_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchStatsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_user_stats_api_v1_stats_reset_user_put: {
        parameters: {
            query: {
                civ_version: string;
                game_type: string;
                discord_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_gen_api_v1_stats_team_gen_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamGenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamGenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_stats_api_v1_stats_user_get: {
        parameters: {
            query: {
                civ_version: string;
                game_type: string;
                discord_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_quit_api_v1_trigger_quit__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["TriggerQuit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_api_v1_update_match__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["MatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_game_report_api_v1_upload_game_report__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_game_report_api_v1_upload_game_report__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    discord_oauth_callback_oauth_discord_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscordOAuthCallbackResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
